alter table content_item drop constraint FK_gudw6viy7lrf5t5hetw7mbgh5;
alter table content_item drop constraint FK_pyrd1nhijag5ct0ee9xqq4h78;
alter table content_item drop constraint FK_9kpe6whsov3ur9rph4ih2vi5a;
alter table global_subscription drop constraint FK_f1l196ykcnh7s2pwo6qnmltw7;
alter table hl7psu_task drop constraint FK_pev4urgkk7id2h1ijhv8domjx;
alter table ian_task drop constraint FK_1fuh251le2hid2byw90hd1mly;
alter table instance drop constraint FK_jxfu47kwjk3kkkyrwewjw8a4n;
alter table instance drop constraint FK_7w6f9bi2w91qr2abl6ddxnrwq;
alter table instance drop constraint FK_s4tgrew4sh4qxoupmk3gihtrk;
alter table instance_req drop constraint FK_cqmmps9maltjybl44t4cck404;
alter table instance_req drop constraint FK_47n586hkafgp9m1etqohgfybl;
alter table location drop constraint FK_hjtlcwsvwihs4khh961d423e7;
alter table location drop constraint FK_bfk5vl6eoxaf0hhwiu3rbgmkn;
alter table mpps drop constraint FK_o49fec996jvdo31o7ysmsn9s2;
alter table mpps drop constraint FK_nrigpgue611m33rao03nnfe5l;
alter table mpps drop constraint FK_ofg0lvfxad6r5oigw3y6da27u;
alter table mwl_item drop constraint FK_6qj8tkh6ib9w2pjqwvqe23ko;
alter table mwl_item drop constraint FK_t4vpsywvy0axeutmdgc0ye3nk;
alter table mwl_item drop constraint FK_hqecoo67sflk190dxyc0hnf0c;
alter table mwl_item drop constraint FK_vkxtls2wr17wgxnxj7b2fe32;
alter table mwl_item drop constraint FK_44qwwvs50lgpog2cqmicxgt1f;
alter table patient drop constraint FK_5lgndn3gn7iug3kuewiy9q124;
alter table patient drop constraint FK_sk77bwjgaoetvy1pbcgqf08g;
alter table patient drop constraint FK_39gahcxyursxfxe2ucextr65s;
alter table patient drop constraint FK_rj42ffdtimnrcwmqqlvj24gi2;
alter table patient drop constraint FK_56r2g5ggptqgcvb3hl11adke2;
alter table rejected_instance drop constraint FK_iafiq2ugv5rd6fonwd0vd7xdx;
alter table rel_study_pcode drop constraint FK_fryhnb2ppb6fcop3jrrfwvnfy;
alter table rel_study_pcode drop constraint FK_mnahh8fh77d365m6w2x4x3f4q;
alter table rel_task_dicomattrs drop constraint FK_e0gtunmen48q8imxggunt7gt7;
alter table rel_task_dicomattrs drop constraint FK_pwaoih2f4ay4c00avvt79de7h;
alter table rel_ups_perf_code drop constraint FK_6asj28yy5se9mp443b6ryefd2;
alter table rel_ups_perf_code drop constraint FK_6m06tt8ku376qxkro94xpteus;
alter table rel_ups_station_class_code drop constraint FK_q26e06qk9gwviwe2ug0f86doa;
alter table rel_ups_station_class_code drop constraint FK_e1ioaswm010jlsq6kl7y3um1c;
alter table rel_ups_station_location_code drop constraint FK_kl60ab0k5c1p8qii9ya16424x;
alter table rel_ups_station_location_code drop constraint FK_9f0l4glqwpq12d11w9osd475m;
alter table rel_ups_station_name_code drop constraint FK_jtv4r8f88f6gfte0fa36w5y9o;
alter table rel_ups_station_name_code drop constraint FK_8jf5xe8ot2yammv3ksd5xrgif;
alter table series drop constraint FK_bdj2kuutidekc2en6dckev7l6;
alter table series drop constraint FK_oiq81nulcmtg6p85iu31igtf5;
alter table series drop constraint FK_avp2oeuufo8axv5j184cchrop;
alter table series drop constraint FK_pu4p7k1o9hleuk9rmxvw2ybj6;
alter table series drop constraint FK_5n4bxxb2xa7bvvq26ao7wihky;
alter table series drop constraint FK_1og1krtgxfh207rtqjg0r7pbd;
alter table series_query_attrs drop constraint FK_eiwosf6pcc97n6y282cv1n54k;
alter table series_req drop constraint FK_bcn0jtvurqutw865pwp34pejb;
alter table series_req drop constraint FK_bdkjk6ww0ulrb0nhf41c7liwt;
alter table soundex_code drop constraint FK_dh7lahwi99hk6bttrk75x4ckc;
alter table sps_station_aet drop constraint FK_js5xqyw5qa9rpttwmck14duow;
alter table study drop constraint FK_5w0oynbw061mwu1rr9mrb6kj4;
alter table study drop constraint FK_e3fdaqhw7u60trs5aspf4sna9;
alter table study drop constraint FK_49eet5qgcsb32ktsqrf1mj3x2;
alter table study_query_attrs drop constraint FK_sxccj81423w8o6w2tsb7nshy9;
alter table subscription drop constraint FK_jadcs2aho4ijh639r67qgk0g0;
alter table ups drop constraint FK_3frtpy5cstsoxk5jxw9cutr33;
alter table ups drop constraint FK_8xiqdli1p8cyw1y4hwyqhimcx;
alter table ups drop constraint FK_1retecpk22a2tysmi5o6xcpbh;
alter table ups_req drop constraint FK_kocdb2pxx2fymu1modhneb4xm;
alter table ups_req drop constraint FK_7vt6m05r0hertks2fcngd5wn1;
alter table verify_observer drop constraint FK_105wt9hglqsmtnoxgma9x18vj;
alter table verify_observer drop constraint FK_qjgrn9rfyyt6sv14utk9ijcfq;
drop table code;
drop table content_item;
drop table dicomattrs;
drop table global_subscription;
drop table hl7psu_task;
drop table ian_task;
drop table id_sequence;
drop table instance;
drop table instance_req;
drop table key_value2;
drop table location;
drop table metadata;
drop table mpps;
drop table mwl_item;
drop table patient;
drop table patient_demographics;
drop table patient_id;
drop table person_name;
drop table rejected_instance;
drop table rel_study_pcode;
drop table rel_task_dicomattrs;
drop table rel_ups_perf_code;
drop table rel_ups_station_class_code;
drop table rel_ups_station_location_code;
drop table rel_ups_station_name_code;
drop table series;
drop table series_query_attrs;
drop table series_req;
drop table soundex_code;
drop table sps_station_aet;
drop table stgcmt_result;
drop table study;
drop table study_query_attrs;
drop table subscription;
drop table task;
drop table uidmap;
drop table ups;
drop table ups_req;
drop table verify_observer;
drop generator code_pk_seq;
drop generator content_item_pk_seq;
drop generator dicomattrs_pk_seq;
drop generator global_subscription_pk_seq;
drop generator hl7psu_task_pk_seq;
drop generator ian_task_pk_seq;
drop generator instance_pk_seq;
drop generator instance_req_pk_seq;
drop generator key_value2_pk_seq;
drop generator location_pk_seq;
drop generator metadata_pk_seq;
drop generator mpps_pk_seq;
drop generator mwl_item_pk_seq;
drop generator patient_id_pk_seq;
drop generator patient_pk_seq;
drop generator person_name_pk_seq;
drop generator rejected_instance_pk_seq;
drop generator series_pk_seq;
drop generator series_query_attrs_pk_seq;
drop generator series_req_pk_seq;
drop generator soundex_code_pk_seq;
drop generator stgcmt_result_pk_seq;
drop generator study_pk_seq;
drop generator study_query_attrs_pk_seq;
drop generator subscription_pk_seq;
drop generator task_pk_seq;
drop generator uidmap_pk_seq;
drop generator ups_pk_seq;
drop generator ups_request_pk_seq;
drop generator verify_observer_pk_seq;
