alter table content_item drop constraint FKfra6ee5jtybfp94ldpvva623o;
alter table content_item drop constraint FK7rpy6unnb5b18b8ieuqr9w9i9;
alter table content_item drop constraint FKei15n1lk1h1e8f89e9ubalm7q;
alter table global_subscription drop constraint FKqkchf2ue2j1p3fv2o94rhacvi;
alter table hl7psu_task drop constraint FKlvjl0o0sdhht440wccag722e4;
alter table ian_task drop constraint FKs3re94tlv0dbd5go33mwdk6dr;
alter table instance drop constraint FKokrgkyvch35m6iwr309mawsna;
alter table instance drop constraint FKqmk050ojwer9ujsbl74d4kf6e;
alter table instance drop constraint FKe92yganh695k2y4hxfqxtesg1;
alter table instance_req drop constraint FK8leut3c0gfxcg6y3lbjlpt2bt;
alter table instance_req drop constraint FKmbg8j00cvubj76doba8funq8j;
alter table location drop constraint FKpp9xjy946uspo3piayc6ofels;
alter table location drop constraint FKendncyyv928u41dfo1x09s644;
alter table mpps drop constraint FKnhstgtx2w1xd61u4iqbn731pu;
alter table mpps drop constraint FK2m3l9bh173bmq88ukf81yd9ow;
alter table mpps drop constraint FKs7mb8qsr1mjijnw9bvx0dhqab;
alter table mwl_item drop constraint FK9vjk41q61e9x9n4qfve6jud8s;
alter table mwl_item drop constraint FKqui6rvqyg1qfujae4mw3o0nbm;
alter table mwl_item drop constraint FKpl6u7oyyp6o3ca8r9jbxv5oge;
alter table mwl_item drop constraint FKeursgxiy2u6ws39cgn1b25e6k;
alter table mwl_item drop constraint FKf5l3x4bfqn3jv8mhj617kidx7;
alter table patient drop constraint FKe8j5c2rhq67rt3opqfggoplt2;
alter table patient drop constraint FKc66cfkdwiu7eq65kgmxilrocw;
alter table patient drop constraint FKig1mwm5jpkyq6733t0hrf56g;
alter table patient drop constraint FKjh4miooi709vj5l6xi8h95f3e;
alter table patient_id drop constraint FKih8d22x50j7orytfmigrnssea;
alter table rejected_instance drop constraint FK27xpx6okj63sunyo76tf0s913;
alter table rel_study_pcode drop constraint FKlia0q74j0xhj2u0avy1wbbx7q;
alter table rel_study_pcode drop constraint FKta5515ogakmavm1swi6tw1n2n;
alter table rel_task_dicomattrs drop constraint FK53sqs6uiua7ff45u94lrv50t7;
alter table rel_task_dicomattrs drop constraint FKhd3dj3u43xxgdxn7w5imp5ank;
alter table rel_ups_perf_code drop constraint FK6om2durembdfk2rmd29dlcm2t;
alter table rel_ups_perf_code drop constraint FK31cp9ux8xb2dcu0nv84tgd8um;
alter table rel_ups_station_class_code drop constraint FK62f8dua3p8bxv3vilctc7pd42;
alter table rel_ups_station_class_code drop constraint FKf0y92ufejerf9dwv8sl6kdkae;
alter table rel_ups_station_location_code drop constraint FKp5d05caciw2cqik5uqt7r8w6p;
alter table rel_ups_station_location_code drop constraint FKlxb9i1b48mfxo0y72fpeoxl48;
alter table rel_ups_station_name_code drop constraint FK308ga4grefjjwmrwtsirjmbhh;
alter table rel_ups_station_name_code drop constraint FKd4gjwmhmlphp865fxiqjypwo2;
alter table series drop constraint FKtih7mdqwcklym58jd9wn3itjq;
alter table series drop constraint FK6nn55bx7pqlmimgfnhfpjra94;
alter table series drop constraint FKnpdeeclrflvuxajeqjmk6utf;
alter table series drop constraint FK84fpblugeadm5u6dw1idi80a0;
alter table series drop constraint FK5p2gub2u40fyh2ch6bp6nan4l;
alter table series drop constraint FK3196nws7ngapmsmtoafb4e88j;
alter table series_query_attrs drop constraint FKsk791fnscydy7whj3lvrp3j1a;
alter table series_req drop constraint FK15lid2bqbrsmjatxiq0vug4wq;
alter table series_req drop constraint FK1gs2u7w7uefvi7dcjg9vlp23x;
alter table soundex_code drop constraint FKctukwjaer0axw2jwv3bfj67r2;
alter table sps_station_aet drop constraint FKmeklscb7t55i8mb2d4cjucywd;
alter table study drop constraint FK2ktu3hbxxalrngfhyp4j6pf70;
alter table study drop constraint FKocnq3so9ej7h0mnd6a6arjf6c;
alter table study drop constraint FKndwmntu3lsjd78erctnbposyr;
alter table study_query_attrs drop constraint FKmu32jq25y6qkimi7hn7d4s2hp;
alter table subscription drop constraint FKh9mdhriyx32gr91pfdgnl48f0;
alter table ups drop constraint FKaddby69vtwxpssgaa12ct6pn3;
alter table ups drop constraint FKjcmu4x6x02r0tc1d28xb3nf17;
alter table ups drop constraint FKr3t1gbo2e42oleaqeastvv5ej;
alter table ups_req drop constraint FK1b5veu90oftv8o95nxx2xndpb;
alter table ups_req drop constraint FKh1sjrdq663dnk8j7hsthun4ie;
alter table verify_observer drop constraint FK8vo3f94xgum0qajsjqnlnqjo4;
alter table verify_observer drop constraint FKkpcwkrsipamdg81mao7nkmdc2;
drop table code;
drop table content_item;
drop table dicomattrs;
drop table global_subscription;
drop table hl7psu_task;
drop table ian_task;
drop table id_sequence;
drop table instance;
drop table instance_req;
drop table key_value2;
drop table location;
drop table metadata;
drop table mpps;
drop table mwl_item;
drop table patient;
drop table patient_demographics;
drop table patient_id;
drop table person_name;
drop table rejected_instance;
drop table rel_study_pcode;
drop table rel_task_dicomattrs;
drop table rel_ups_perf_code;
drop table rel_ups_station_class_code;
drop table rel_ups_station_location_code;
drop table rel_ups_station_name_code;
drop table series;
drop table series_query_attrs;
drop table series_req;
drop table soundex_code;
drop table sps_station_aet;
drop table stgcmt_result;
drop table study;
drop table study_query_attrs;
drop table subscription;
drop table task;
drop table uidmap;
drop table ups;
drop table ups_req;
drop table verify_observer;
