drop table code cascade constraints;
drop table content_item cascade constraints;
drop table dicomattrs cascade constraints;
drop table global_subscription cascade constraints;
drop table hl7psu_task cascade constraints;
drop table ian_task cascade constraints;
drop table id_sequence cascade constraints;
drop table instance cascade constraints;
drop table instance_req cascade constraints;
drop table key_value2 cascade constraints;
drop table location cascade constraints;
drop table metadata cascade constraints;
drop table mpps cascade constraints;
drop table mwl_item cascade constraints;
drop table patient cascade constraints;
drop table patient_demographics cascade constraints;
drop table patient_id cascade constraints;
drop table person_name cascade constraints;
drop table rejected_instance cascade constraints;
drop table rel_study_pcode cascade constraints;
drop table rel_task_dicomattrs cascade constraints;
drop table rel_ups_perf_code cascade constraints;
drop table rel_ups_station_class_code cascade constraints;
drop table rel_ups_station_location_code cascade constraints;
drop table rel_ups_station_name_code cascade constraints;
drop table series cascade constraints;
drop table series_query_attrs cascade constraints;
drop table series_req cascade constraints;
drop table soundex_code cascade constraints;
drop table sps_station_aet cascade constraints;
drop table stgcmt_result cascade constraints;
drop table study cascade constraints;
drop table study_query_attrs cascade constraints;
drop table subscription cascade constraints;
drop table task cascade constraints;
drop table uidmap cascade constraints;
drop table ups cascade constraints;
drop table ups_req cascade constraints;
drop table verify_observer cascade constraints;
drop sequence code_pk_seq;
drop sequence content_item_pk_seq;
drop sequence dicomattrs_pk_seq;
drop sequence global_subscription_pk_seq;
drop sequence hl7psu_task_pk_seq;
drop sequence ian_task_pk_seq;
drop sequence instance_pk_seq;
drop sequence instance_req_pk_seq;
drop sequence key_value2_pk_seq;
drop sequence location_pk_seq;
drop sequence metadata_pk_seq;
drop sequence mpps_pk_seq;
drop sequence mwl_item_pk_seq;
drop sequence patient_id_pk_seq;
drop sequence patient_pk_seq;
drop sequence person_name_pk_seq;
drop sequence rejected_instance_pk_seq;
drop sequence series_pk_seq;
drop sequence series_query_attrs_pk_seq;
drop sequence series_req_pk_seq;
drop sequence soundex_code_pk_seq;
drop sequence stgcmt_result_pk_seq;
drop sequence study_pk_seq;
drop sequence study_query_attrs_pk_seq;
drop sequence subscription_pk_seq;
drop sequence task_pk_seq;
drop sequence uidmap_pk_seq;
drop sequence ups_pk_seq;
drop sequence ups_request_pk_seq;
drop sequence verify_observer_pk_seq;
