set client_min_messages = WARNING;
alter table if exists content_item drop constraint if exists FKfra6ee5jtybfp94ldpvva623o;
alter table if exists content_item drop constraint if exists FK7rpy6unnb5b18b8ieuqr9w9i9;
alter table if exists content_item drop constraint if exists FKei15n1lk1h1e8f89e9ubalm7q;
alter table if exists global_subscription drop constraint if exists FKqkchf2ue2j1p3fv2o94rhacvi;
alter table if exists hl7psu_task drop constraint if exists FKlvjl0o0sdhht440wccag722e4;
alter table if exists ian_task drop constraint if exists FKs3re94tlv0dbd5go33mwdk6dr;
alter table if exists instance drop constraint if exists FKokrgkyvch35m6iwr309mawsna;
alter table if exists instance drop constraint if exists FKqmk050ojwer9ujsbl74d4kf6e;
alter table if exists instance drop constraint if exists FKe92yganh695k2y4hxfqxtesg1;
alter table if exists instance_req drop constraint if exists FK8leut3c0gfxcg6y3lbjlpt2bt;
alter table if exists instance_req drop constraint if exists FKmbg8j00cvubj76doba8funq8j;
alter table if exists location drop constraint if exists FKpp9xjy946uspo3piayc6ofels;
alter table if exists location drop constraint if exists FKendncyyv928u41dfo1x09s644;
alter table if exists mpps drop constraint if exists FKnhstgtx2w1xd61u4iqbn731pu;
alter table if exists mpps drop constraint if exists FK2m3l9bh173bmq88ukf81yd9ow;
alter table if exists mpps drop constraint if exists FKs7mb8qsr1mjijnw9bvx0dhqab;
alter table if exists mwl_item drop constraint if exists FK9vjk41q61e9x9n4qfve6jud8s;
alter table if exists mwl_item drop constraint if exists FKqui6rvqyg1qfujae4mw3o0nbm;
alter table if exists mwl_item drop constraint if exists FKpl6u7oyyp6o3ca8r9jbxv5oge;
alter table if exists mwl_item drop constraint if exists FKeursgxiy2u6ws39cgn1b25e6k;
alter table if exists mwl_item drop constraint if exists FKf5l3x4bfqn3jv8mhj617kidx7;
alter table if exists patient drop constraint if exists FKe8j5c2rhq67rt3opqfggoplt2;
alter table if exists patient drop constraint if exists FKc66cfkdwiu7eq65kgmxilrocw;
alter table if exists patient drop constraint if exists FKig1mwm5jpkyq6733t0hrf56g;
alter table if exists patient drop constraint if exists FKjh4miooi709vj5l6xi8h95f3e;
alter table if exists patient_id drop constraint if exists FKih8d22x50j7orytfmigrnssea;
alter table if exists rejected_instance drop constraint if exists FK27xpx6okj63sunyo76tf0s913;
alter table if exists rel_study_pcode drop constraint if exists FKlia0q74j0xhj2u0avy1wbbx7q;
alter table if exists rel_study_pcode drop constraint if exists FKta5515ogakmavm1swi6tw1n2n;
alter table if exists rel_task_dicomattrs drop constraint if exists FK53sqs6uiua7ff45u94lrv50t7;
alter table if exists rel_task_dicomattrs drop constraint if exists FKhd3dj3u43xxgdxn7w5imp5ank;
alter table if exists rel_ups_perf_code drop constraint if exists FK6om2durembdfk2rmd29dlcm2t;
alter table if exists rel_ups_perf_code drop constraint if exists FK31cp9ux8xb2dcu0nv84tgd8um;
alter table if exists rel_ups_station_class_code drop constraint if exists FK62f8dua3p8bxv3vilctc7pd42;
alter table if exists rel_ups_station_class_code drop constraint if exists FKf0y92ufejerf9dwv8sl6kdkae;
alter table if exists rel_ups_station_location_code drop constraint if exists FKp5d05caciw2cqik5uqt7r8w6p;
alter table if exists rel_ups_station_location_code drop constraint if exists FKlxb9i1b48mfxo0y72fpeoxl48;
alter table if exists rel_ups_station_name_code drop constraint if exists FK308ga4grefjjwmrwtsirjmbhh;
alter table if exists rel_ups_station_name_code drop constraint if exists FKd4gjwmhmlphp865fxiqjypwo2;
alter table if exists series drop constraint if exists FKtih7mdqwcklym58jd9wn3itjq;
alter table if exists series drop constraint if exists FK6nn55bx7pqlmimgfnhfpjra94;
alter table if exists series drop constraint if exists FKnpdeeclrflvuxajeqjmk6utf;
alter table if exists series drop constraint if exists FK84fpblugeadm5u6dw1idi80a0;
alter table if exists series drop constraint if exists FK5p2gub2u40fyh2ch6bp6nan4l;
alter table if exists series drop constraint if exists FK3196nws7ngapmsmtoafb4e88j;
alter table if exists series_query_attrs drop constraint if exists FKsk791fnscydy7whj3lvrp3j1a;
alter table if exists series_req drop constraint if exists FK15lid2bqbrsmjatxiq0vug4wq;
alter table if exists series_req drop constraint if exists FK1gs2u7w7uefvi7dcjg9vlp23x;
alter table if exists soundex_code drop constraint if exists FKctukwjaer0axw2jwv3bfj67r2;
alter table if exists sps_station_aet drop constraint if exists FKmeklscb7t55i8mb2d4cjucywd;
alter table if exists study drop constraint if exists FK2ktu3hbxxalrngfhyp4j6pf70;
alter table if exists study drop constraint if exists FKocnq3so9ej7h0mnd6a6arjf6c;
alter table if exists study drop constraint if exists FKndwmntu3lsjd78erctnbposyr;
alter table if exists study_query_attrs drop constraint if exists FKmu32jq25y6qkimi7hn7d4s2hp;
alter table if exists subscription drop constraint if exists FKh9mdhriyx32gr91pfdgnl48f0;
alter table if exists ups drop constraint if exists FKaddby69vtwxpssgaa12ct6pn3;
alter table if exists ups drop constraint if exists FKhy3cd5se2avt08upapu19y1g6;
alter table if exists ups drop constraint if exists FKjcmu4x6x02r0tc1d28xb3nf17;
alter table if exists ups drop constraint if exists FKr3t1gbo2e42oleaqeastvv5ej;
alter table if exists ups_req drop constraint if exists FK1b5veu90oftv8o95nxx2xndpb;
alter table if exists ups_req drop constraint if exists FKh1sjrdq663dnk8j7hsthun4ie;
alter table if exists verify_observer drop constraint if exists FK8vo3f94xgum0qajsjqnlnqjo4;
alter table if exists verify_observer drop constraint if exists FKkpcwkrsipamdg81mao7nkmdc2;
drop table if exists code cascade;
drop table if exists content_item cascade;
drop table if exists dicomattrs cascade;
drop table if exists global_subscription cascade;
drop table if exists hl7psu_task cascade;
drop table if exists ian_task cascade;
drop table if exists id_sequence cascade;
drop table if exists instance cascade;
drop table if exists instance_req cascade;
drop table if exists key_value2 cascade;
drop table if exists location cascade;
drop table if exists metadata cascade;
drop table if exists mpps cascade;
drop table if exists mwl_item cascade;
drop table if exists patient cascade;
drop table if exists patient_demographics cascade;
drop table if exists patient_id cascade;
drop table if exists person_name cascade;
drop table if exists rejected_instance cascade;
drop table if exists rel_study_pcode cascade;
drop table if exists rel_task_dicomattrs cascade;
drop table if exists rel_ups_perf_code cascade;
drop table if exists rel_ups_station_class_code cascade;
drop table if exists rel_ups_station_location_code cascade;
drop table if exists rel_ups_station_name_code cascade;
drop table if exists series cascade;
drop table if exists series_query_attrs cascade;
drop table if exists series_req cascade;
drop table if exists soundex_code cascade;
drop table if exists sps_station_aet cascade;
drop table if exists stgcmt_result cascade;
drop table if exists study cascade;
drop table if exists study_query_attrs cascade;
drop table if exists subscription cascade;
drop table if exists task cascade;
drop table if exists uidmap cascade;
drop table if exists ups cascade;
drop table if exists ups_req cascade;
drop table if exists verify_observer cascade;
drop sequence if exists code_pk_seq;
drop sequence if exists content_item_pk_seq;
drop sequence if exists dicomattrs_pk_seq;
drop sequence if exists global_subscription_pk_seq;
drop sequence if exists hl7psu_task_pk_seq;
drop sequence if exists ian_task_pk_seq;
drop sequence if exists instance_pk_seq;
drop sequence if exists instance_req_pk_seq;
drop sequence if exists key_value2_pk_seq;
drop sequence if exists location_pk_seq;
drop sequence if exists metadata_pk_seq;
drop sequence if exists mpps_pk_seq;
drop sequence if exists mwl_item_pk_seq;
drop sequence if exists patient_id_pk_seq;
drop sequence if exists patient_pk_seq;
drop sequence if exists person_name_pk_seq;
drop sequence if exists rejected_instance_pk_seq;
drop sequence if exists series_pk_seq;
drop sequence if exists series_query_attrs_pk_seq;
drop sequence if exists series_req_pk_seq;
drop sequence if exists soundex_code_pk_seq;
drop sequence if exists stgcmt_result_pk_seq;
drop sequence if exists study_pk_seq;
drop sequence if exists study_query_attrs_pk_seq;
drop sequence if exists subscription_pk_seq;
drop sequence if exists task_pk_seq;
drop sequence if exists uidmap_pk_seq;
drop sequence if exists ups_pk_seq;
drop sequence if exists ups_request_pk_seq;
drop sequence if exists verify_observer_pk_seq;
